### ISSUE TITLE
Feature: support circuitbreak on kitex proxyless client

### ISSUE THREAD

**Issue by whalecold** [kitex-contrib/xds#27]
**Is your feature request related to a problem? Please describe.**

Kitex 当前支持配置熔断策略。Istio 目前的治理策略还不支持，[envoy proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto) 是支持的，可以通过 envoyfilter 进行 patch。

**Describe the solution you'd like**

Kitex 重试使用参见：https://www.cloudwego.io/zh/docs/kitex/tutorials/service-governance/circuitbreaker/
envoy proxy xDS 中的配置如下：
```
{
  "consecutive_5xx": {...},
  "interval": {...},
  "base_ejection_time": {...},
  "max_ejection_percent": {...},
  "enforcing_consecutive_5xx": {...},
  "enforcing_success_rate": {...},
  "success_rate_minimum_hosts": {...},
  "success_rate_request_volume": {...},
  "success_rate_stdev_factor": {...},
  "consecutive_gateway_failure": {...},
  "enforcing_consecutive_gateway_failure": {...},
  "split_external_local_origin_errors": ...,
  "consecutive_local_origin_failure": {...},
  "enforcing_consecutive_local_origin_failure": {...},
  "enforcing_local_origin_success_rate": {...},
  "failure_percentage_threshold": {...},
  "enforcing_failure_percentage": {...},
  "enforcing_failure_percentage_local_origin": {...},
  "failure_percentage_minimum_hosts": {...},
  "failure_percentage_request_volume": {...},
  "max_ejection_time": {...},
  "max_ejection_time_jitter": {...},
  "successful_active_health_check_uneject_host": {...}
}
```
其中参数 `failure_percentage_threshold` 和 `failure_percentage_threshold` 可以和 Kitex 中的熔断策略对齐

**Describe alternatives you've considered**

**Additional context**

**Comment by ppzqh** [comment]
This feature has been merged. Thanks @whalecold for the contribution.
